Feature/hawk 7/create custom view title edit text
codex-team/hawk.android pull request #12
Opened 2020-11-01 22:32 UTC by temnik15

Solution to issue 7.
There is a question about the finished implementation: What should the .getText () method, a string or an object of type CharSequence return?

2020-11-02 06:21 UTC, Shiplayer requested changes

2020-11-02 06:21 UTC, Shiplayer commented on app/src/main/res/drawable/edit_text_back.xml
> +    <stroke android:color="@color/editTextBorder" android:width="@dimen/default_border"/>
в пулл реквесте нет таких значений, может забыл их добавить в коммит?

2020-11-02 06:21 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/custom/views/TitleEditText.kt
> +    fun setTitle(newTitle: CharSequence) {
Надо описывать не только сам метод, но и параметры функции и возвращаемые значения

2020-11-02 10:47 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/custom/views/TitleEditText.kt
> +    fun setTitle(newTitle: CharSequence) {
@Shiplayer, а что как раз по возвращаемому значению из getText()? Возвращать тип String или же оставить это уже на решение пользователя и отдавать CharSequence?

2020-11-02 11:20 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/custom/views/TitleEditText.kt
> +    fun setTitle(newTitle: CharSequence) {
Я не про конкретный метод говорил, у тебя ниже методы, где нет документации на возвращаемся тип.

2020-11-02 11:47 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/custom/views/TitleEditText.kt
> +    fun setTitle(newTitle: CharSequence) {
для данного метода необходимо добавить документацию для аргументов

2020-11-02 19:24 UTC, Shiplayer approved these changes

2020-11-03 17:58 UTC, neSpecc commented on app/src/main/java/so/codex/hawk/custom/views/TitleEditText.kt
> +     * @param newTitle The method accepts any type that implements
тут тоже не хватает отступа и выравнивания

2020-11-03 18:28 UTC, neSpecc approved these changes

2020-11-03 19:04 UTC, merged