Feature/hawk-6/create-auth-ui
codex-team/hawk.android pull request #14
Opened 2020-11-04 12:00 UTC by temnik15

Created a UI for the login screen and set it as the start screen.

2020-11-04 18:37 UTC, Shiplayer requested changes
Необходимо еще добавить шрифт, которые указаны в макетах

2020-11-04 18:37 UTC, Shiplayer commented on app/src/main/res/layout/activity_login.xml
> +            android:layout_marginStart="@dimen/default_margin"
вынести такой отступ в родительский элемент, как паддинг, так как много где используется

2020-11-04 18:37 UTC, Shiplayer commented on app/src/main/res/layout/activity_login.xml
> +            android:layout_width="wrap_content"
предлагаю отказаться от паддингов и сделать минимальную ширину для кнопки

2020-11-04 19:44 UTC, temnik15 commented
Github не дает прикрепить apk, поэтому вот ссылка на google диск с apk для тестирования.
https://drive.google.com/file/d/1MfczQb8YzouZTRPyeUiWtL79SawDe8p2/view?usp=sharing

2020-11-06 21:17 UTC, Shiplayer requested changes
Поставить для всех TextView поле includeFontPadding="false"

2020-11-06 21:17 UTC, Shiplayer commented on app/src/main/AndroidManifest.xml
> +            android:resource="@array/preloaded_fonts" />
зачем нам динамически загружаемые шрифты?

2020-11-06 21:17 UTC, Shiplayer commented on app/src/main/res/values/font_certs.xml
> +<?xml version="1.0" encoding="utf-8"?>
это ведь тянется для динамически подгружаемых шрифтов?

2020-11-07 20:02 UTC, temnik15 commented on app/src/main/res/values/font_certs.xml
> +<?xml version="1.0" encoding="utf-8"?>
Да, ошибся пунктом при установке.

2020-11-07 21:10 UTC, Shiplayer commented
Необходимо еще исправить конфликт с основной веткой

2020-11-07 21:11 UTC, Shiplayer approved these changes

2020-11-12 15:33 UTC, nikmel2803 approved these changes

2020-11-12 15:34 UTC, neSpecc approved these changes

2020-11-12 21:54 UTC, merged