#8/create a class for savind session
codex-team/hawk.android pull request #22
Opened 2020-11-08 12:48 UTC by temnik15

A class has been created to persist the session while the application is running and for long-term storage. 
Set the initialization of this class when starting the application

2020-11-08 13:02 UTC, Shiplayer commented on app/build.gradle
> +    implementation group: 'io.reactivex.rxjava3', name: 'rxjava', version: '3.0.0-RC1'
Зачем две одинаковых зависимости?

2020-11-08 13:02 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/SessionKeeper.kt
> +        this.context = context
Может стоит как то обезопасить этот момент? Хотя бы бросить эксепшен, если попытаться его заново инициализировать

2020-11-08 13:02 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/SessionKeeper.kt
> +    private fun getSessionFromPref(preferences: SharedPreferences) {
Не похоже, чтобы он что-то возвращал

2020-11-08 14:40 UTC, temnik15 commented on app/build.gradle
> +    implementation group: 'io.reactivex.rxjava3', name: 'rxjava', version: '3.0.0-RC1'
@Shiplayer разве они одинаковые? без второй с name 'android' становятся не доступны возможности RxJava для android (Например AndroidSchedulers.mainThread() из io.reactivex.rxjava3.android.schedulers.AndroidSchedulers

2020-11-08 14:55 UTC, Shiplayer commented on app/build.gradle
> +    implementation group: 'io.reactivex.rxjava3', name: 'rxjava', version: '3.0.0-RC1'
Наверное, не заметил, что name был разный

2020-11-08 14:56 UTC, Shiplayer commented on app/build.gradle
> +    implementation group: 'io.reactivex.rxjava3', name: 'rxjava', version: '3.0.0-RC1'
Подними лучше у rxjava до 3.0.7

2020-11-08 14:57 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/SessionKeeper.kt
> +        this.context = context
Я тут думаю, может лучше не исключение кидать, а просто проверять через if что поле уже инициализировано? и все последующие вызовы не будут никак влиять

2020-11-08 15:08 UTC, Shiplayer requested changes

2020-11-08 15:08 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/SessionKeeper.kt
> +    const val KEY_ACCESS_TOKEN = "ACCESS_TOKEN"
Почему такие поля не приватные?

2020-11-08 15:08 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/SessionKeeper.kt
> +    fun subscribeToSessionUpdate(observer: Observer<Pair<String, String>>) {
Я думаю, что лучше не запрашивать обзервер, а предоставлять обсервабл, чтобы они решали, где им подписываться

2020-11-08 15:08 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/SessionKeeper.kt
> +    fun subscribeToSessionUpdate(observer: Observer<Pair<String, String>>) {
Так ещё получается, что этот подписчик никогда не отпишется и будет меморилик

2020-11-08 15:09 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/SessionKeeper.kt
> +    const val KEY_ACCESS_TOKEN = "ACCESS_TOKEN"
Это как раз то о чем я хотел рассказать при созвоне) Есть один нюанс с пробросом обновления сессии подписчикам

2020-11-09 12:25 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/SessionKeeper.kt
> +    fun getObservableSession(): Observable<Pair<String, String>> {
почему Pair? может нам стоит возвращать Session или просто Token

2020-11-09 13:10 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/entity/Session.kt
> +data class Token(val accessToken: String, val refreshToken: String)
Добавь документацию

2020-11-09 13:10 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/HawkApp.kt
> +}
И сюда тоже документацию добавь

2020-11-09 13:10 UTC, Shiplayer commented on app/build.gradle
> +    implementation group: 'io.reactivex.rxjava3', name: 'rxandroid', version: '3.0.0'
Сделай над общим коммитом и чтобы выглядело однообразно
```suggestion

    // RxJava 3
    implementation 'io.reactivex.rxjava3:rxjava:3.0.7'
    implementation 'io.reactivex.rxjava3:rxandroid:3.0.0'
```

2020-11-09 13:20 UTC, Shiplayer reviewed
отформатируй код

2020-11-09 13:20 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/entity/Session.kt
> +data class Session(val token:Token,val time:Long)
пробел после , поставь и после :

2020-11-11 11:25 UTC, Shiplayer requested changes

2020-11-11 11:25 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/SessionKeeper.kt
> +                    prefSubject.onNext(Token(value, ""))
почему мы должны отправлять только accessToken, если у нас изменились все данные?
мы ведь знаем, что уведомлять слушателей будут уже после того, как все указанные данные изменятся в файле

2020-11-11 11:25 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/SessionKeeper.kt
> +                    prefSubject.onNext(Token(value, ""))
думаю, что тут можно будет воспользоваться методом `restoreSessionFromPref` и после него отправить данные в сабджект

2020-11-11 19:18 UTC, Shiplayer approved these changes

2020-11-12 15:34 UTC, nikmel2803 approved these changes

2020-11-12 22:18 UTC, merged