#20: add container and logic to display notification on host
codex-team/hawk.android pull request #30
Opened 2020-11-16 22:30 UTC by Shiplayer

#20

2020-11-17 00:27 UTC, temnik15 requested changes

2020-11-17 00:27 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/LoginActivity.kt
> +            )
Это ты просто тестировал?

2020-11-17 00:27 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/custom/views/NotificationContainerView.kt
> +    private fun statusBarIsVisible(context: Context): Boolean {
Нет описания возвращаемого значения

2020-11-17 21:17 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/LoginActivity.kt
> +            )
ага

2020-11-17 21:36 UTC, temnik15 approved these changes

2020-11-19 12:38 UTC, nikmel2803 approved these changes

2020-11-19 13:20 UTC, merged