Feature/hawk-25/add-view-model-for-auth
codex-team/hawk.android pull request #32
Opened 2020-11-17 02:11 UTC by temnik15

Added ViewModel and LoginInteractor to handle login events.

2020-11-17 21:40 UTC, Shiplayer requested changes

2020-11-17 21:40 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/login/LoginViewModel.kt
> +            loginInteractor.getLoginEventObservable().observeOn(AndroidSchedulers.mainThread())
делай лучше такую цепочку вызовов с новой строчки, улучшает читаемость

2020-11-17 21:40 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/login/LoginActivity.kt
> +    private lateinit var loginViewModel: LoginViewModel
почему бы его сразу не получить через ленивую инициализацию?

2020-11-17 21:40 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/domain/login/LoginInteractorImpl.kt
> +            }.map {
с новой строчки

2020-11-17 21:40 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/domain/login/LoginInteractorImpl.kt
> +                    for (error in it.errors!!) {
опасно это, так как, если выше мы проверим, что `it.error == null` вернет `true`, а условие `it.data != null` вернет `false`, то мы попадем на это условие, где уже получим NPE из за `!!` знаков, можешь поменять на оператор элвиса
```suggestion
                    for (error in it.errors ?: listOf()) {
```

2020-11-17 21:41 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/domain/login/LoginInteractorImpl.kt
> +                client.rxMutate(LoginMutation(it.email, it.password))
давай тут явно укажем, чтобы он выполнялся в io потоке?

2020-11-17 21:44 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/domain/login/LoginInteractorImpl.kt
> +                client.rxMutate(LoginMutation(it.email, it.password))
ну так внизу subscribeOn есть же? Он применится на операции выше себя, ручками я проверил, там io. Или же все таки еще явно указать?

2020-11-17 21:45 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/domain/login/LoginInteractorImpl.kt
> +                client.rxMutate(LoginMutation(it.email, it.password))
ну так внизу subscribeOn есть же? Он применится на операции выше себя, ручками я проверил, там io. Или же все таки еще явно указать?

2020-11-17 21:46 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/domain/login/LoginInteractorImpl.kt
> +                client.rxMutate(LoginMutation(it.email, it.password))
давай его лучше просто повыше перенесем?

2020-11-17 22:14 UTC, neSpecc approved these changes

2020-11-18 07:24 UTC, Shiplayer requested changes

2020-11-18 07:24 UTC, Shiplayer commented on app/build.gradle
> +    annotationProcessor "android.arch.lifecycle:compiler:1.1.1"
почему используются зависимости для android? у нас же проект построен на androidx

2020-11-18 07:24 UTC, Shiplayer commented on app/build.gradle
> +    annotationProcessor "android.arch.lifecycle:compiler:1.1.1"
и вообще, какая то старая версия используется
https://developer.android.com/jetpack/androidx/releases/lifecycle?hl=ru

2020-11-18 18:54 UTC, temnik15 commented on app/build.gradle
> +    annotationProcessor "android.arch.lifecycle:compiler:1.1.1"
хм,, странно, используется верный пакет с androidx)) Заменил на // ViewModel
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:$lifecycle_version"
    // LiveData
    implementation "androidx.lifecycle:lifecycle-livedata-ktx:$lifecycle_version"

2020-11-18 21:00 UTC, Shiplayer approved these changes

2020-11-18 22:06 UTC, merged