Feature/hawk-27/add-splash-screen
codex-team/hawk.android pull request #36
Opened 2020-11-22 19:27 UTC by temnik15

Created activities for splash screen. 
The activity checks the freshness of the access token and, if it is valid, redirects to the main screen (MainActivity) otherwise to the authorization screen (LoginActivity). 
Error events are not handled.

2020-11-29 07:15 UTC, Shiplayer requested changes

2020-11-29 07:15 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/domain/refresh/RefreshTokenInteractorImpl.kt
> +            .switchMapSingle {
Наверное, стоит сделать distinctUntilChanged, чтобы мы каждый раз не switchMapSingle не делали, а только если Token поменяется

2020-11-29 07:15 UTC, Shiplayer commented on app/src/main/res/layout/activity_splash.xml
> +        android:translationZ="-1dp"
зачем тут -1dp?

2020-11-29 07:15 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/extensions/apollo/response.kt
> +        RefreshResponse(Token("", ""), hasError = true, errors)
Вроде договаривались сделать какую-то константу, когда у нас токен не валидный?

2020-11-29 07:15 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/extensions/apollo/response.kt
> +        RefreshResponse(Token("", ""), hasError = true, errors)
это касается Token("", "")

2020-11-29 07:15 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/domain/refresh/RefreshTokenInteractorImpl.kt
> +    private val refreshObservable = createRefreshEventObservable()
Зачем заводить отдельную переменную?

2020-11-29 09:30 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/domain/refresh/RefreshTokenInteractorImpl.kt
> +            .switchMapSingle {
добавил

2020-11-29 20:26 UTC, Shiplayer approved these changes

2020-11-30 19:40 UTC, YorkIsMine approved these changes

2020-11-30 20:23 UTC, neSpecc approved these changes

2020-11-30 20:57 UTC, merged