feature/hawk-37/create-a-squircle-image-view
codex-team/hawk.android pull request #43
Opened 2020-12-03 20:02 UTC by temnik15

Created a custom view that can crop nested content to fit the squircle.
![git](https://user-images.githubusercontent.com/45372245/101081689-73081c80-35bb-11eb-973b-1acbee79b390.jpg)

2020-12-04 20:10 UTC, Shiplayer requested changes

2020-12-04 20:10 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/custom/views/SquircleImageView.kt
> +            path = createSquirclePath()
Может стоит посчитать путь до того, как мы будем отрисовывать вьюшку?

2020-12-04 20:10 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/custom/views/SquircleImageView.kt
> +            isOnMeasureWorked = false
Не особо понимаю, для чего это поле?

2020-12-04 20:12 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/custom/views/SquircleImageView.kt
> +            path = createSquirclePath()
А это разве возможно ? При инициализации размеров ещё нет, или стоит из атрибутов тащить, а не полагаться на onMeasure?

2020-12-04 20:16 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/custom/views/SquircleImageView.kt
> +            path = createSquirclePath()
разве мы не можем это сделать в onSizeChanged()?
https://stackoverflow.com/questions/3526148/when-is-onsizechanged-called

2020-12-04 20:39 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/custom/views/SquircleImageView.kt
> +            isOnMeasureWorked = false
Удалил данное поле. В нем нет необходимости после переноса метода построения пути в другое место.

2020-12-04 20:40 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/custom/views/SquircleImageView.kt
> +            path = createSquirclePath()
можем, перенес создание пути в onSizeChanged()

2020-12-05 20:09 UTC, Shiplayer approved these changes

2020-12-06 14:38 UTC, YorkIsMine requested changes

2020-12-06 14:38 UTC, YorkIsMine commented on app/src/main/java/so/codex/hawk/custom/views/SquircleImageView.kt
> +        val y = abs(Math.E.pow(ln(base) / n))
можно сократить до abs(корень n-ой степени из base)

2020-12-06 14:38 UTC, YorkIsMine commented on app/src/main/java/so/codex/hawk/custom/views/SquircleImageView.kt
> +        }
в целом можно сделать и покрасивее. На твое усмотрение в общем

2020-12-06 14:39 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/custom/views/SquircleImageView.kt
> +        val y = abs(Math.E.pow(ln(base) / n))
поправил)

2020-12-06 14:39 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/custom/views/SquircleImageView.kt
> +        }
можно конечно одним циклом, и потом склеить два пути, но читаемость заметно упадет, предлагаю оставить так

2020-12-06 14:43 UTC, YorkIsMine approved these changes

2020-12-09 07:09 UTC, YorkIsMine approved these changes

2020-12-09 17:30 UTC, merged