Bug/hawk 44/fix display of notification queue
codex-team/hawk.android pull request #45
Opened 2020-12-06 15:55 UTC by temnik15

Bug fixes with displaying the notifications queue

2020-12-06 21:50 UTC, Shiplayer requested changes

2020-12-06 21:50 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/custom/views/NotificationContainerView.kt
> +    private val queueNotification = mutableListOf<FrameLayout>()
Может можно как то хранить модельки, чем FrameLayout?

2020-12-06 21:50 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/custom/views/NotificationContainerView.kt
> +        }
Не хотелось бы плодить логику очередей во вьюшке, я думаю, что это должен делать внешний класс

2020-12-06 21:51 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/custom/views/NotificationContainerView.kt
> +        }
Я вообще думал вынести её в presenter, просто тут уже есть Handler..ну я подумаю

2020-12-07 13:16 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/custom/views/NotificationContainerView.kt
> +    private val queueNotification = mutableListOf<FrameLayout>()
исправил

2020-12-07 13:18 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/custom/views/NotificationContainerView.kt
> +        }
Во общем, я решил что вытягивать всю логику куда-то еще (контейнер или презентер) слишком запутанно, тем более ты первоначально работал с Lopper внутри view, поэтому я поправил баг с твоей view и сделал еще одну, которую унаследовал и добавил функционал отображения очереди уведомлений

2020-12-07 13:21 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/custom/views/NotificationContainerView.kt
> +        }
почему этим должна заниматься вьюшка, а не NotificationManager?

2020-12-07 13:22 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/custom/views/NotificationContainerView.kt
> +        }
пусть вьюшка проверяет, есть ли уже нотификация или нет, чтобы ее можно было перекрыть, а NotificationManager решает, когда и что надо показывать

2020-12-07 13:25 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/custom/views/NotificationContainerView.kt
> +        }
окей

2020-12-07 13:30 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/custom/views/NotificationContainerView.kt
> +        }
там просто проблема есть, у тебя между NotificationManager и view есть прокладка в виде NotificationContainer, а мне для работы нужна ссылка на эту view, но тащить еще дальше не хочется..может тогда лучше пускай NotificationContainer этим занимается?

2020-12-07 13:32 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/custom/views/NotificationContainerView.kt
> +        }
а нет, есть еще вариант, ладно чуть попозже позову посмотреть

2020-12-07 22:23 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/custom/views/NotificationContainerView.kt
> +        }
Отказались от очереди уведомлений.

2020-12-08 20:38 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/custom/views/NotificationContainerView.kt
> +        Timber.i("New notification received.")
предлагаю сделать проверку, если мы уже что-то показываем, то пишем в логи с ошибкой

2020-12-08 20:39 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/custom/views/NotificationContainerView.kt
> +        Timber.i("New notification received.")
Ок

2020-12-11 06:31 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/custom/views/NotificationContainerView.kt
> +        notification.clipToOutline = true
давай вынесем это в отдельную функцию, которая будет возвращать FrameLayout

2020-12-11 06:31 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/custom/views/NotificationContainerView.kt
>          message.gravity = Gravity.CENTER
а это вынесем в функцию для создания контента, будем возвращать в методе для создания notification

2020-12-11 06:31 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/custom/views/NotificationContainerView.kt
>          }
это тоже вынести в метод к 1 комментарию

2020-12-15 22:22 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/custom/views/NotificationContainerView.kt
> +        notification.clipToOutline = true
solved

2020-12-15 22:22 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/custom/views/NotificationContainerView.kt
>          message.gravity = Gravity.CENTER
solved

2020-12-15 22:31 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/custom/views/NotificationContainerView.kt
> +        Timber.i("New notification received.")
Ведь это просто текст, что мы пытаемся показать новое уведомление и оно не говорит нам, что мы уже что то показываем

2020-12-15 22:33 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/custom/views/NotificationContainerView.kt
> +        Timber.i("New notification received.")
уже поправил давно, через минуту залью последнюю версию

2020-12-15 22:35 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/custom/views/NotificationContainerView.kt
> +            Timber.e("Forced replacement of notification!")
@Shiplayer, а, даже тут уже есть эти изменения

2020-12-16 20:00 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/custom/views/NotificationContainerView.kt
>          }
почему бы тут просто не вызвать `hideNotification()`?

2020-12-16 20:03 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/custom/views/NotificationContainerView.kt
>          }
Исправлю. Данный кусок использовался для потомка, умеющего отображать очередь сообщений и там для корректной работы callback требовался  именно такой вариант)

2020-12-16 20:05 UTC, Shiplayer approved these changes
- [x] заменить условие для удаления старой коммуникации в `updateNotification` на вызов метода `hideNotification()`

2020-12-19 09:11 UTC, YorkIsMine approved these changes

2020-12-19 17:37 UTC, merged