Create custom search view
codex-team/hawk.android pull request #46
Opened 2020-12-11 18:08 UTC by YorkIsMine

2020-12-11 19:00 UTC, temnik15 requested changes

2020-12-11 19:00 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/custom/views/HawkSearchView.kt
> +
Не забудь документацию оформить

2020-12-11 19:00 UTC, temnik15 commented on app/src/main/res/layout/search_view_layout.xml
> +    android:layout_height="36dp"
А тут все в ресурсы вынести

2020-12-20 19:59 UTC, temnik15 commented on app/src/main/res/layout/search_view_layout.xml
> +        android:textColor="#DBE6FF"
цвета тоже можно вынести, там даже для текста  уже есть такой цвет

2020-12-22 11:28 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/ui/main/MainActivity.kt
> +                text = "Hello",
не понял, а зачем сразу hello?

2020-12-22 11:28 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/main/MainActivity.kt
> +                text = "Hello",
тестовый пример

2020-12-22 11:30 UTC, temnik15 approved these changes

2020-12-22 11:30 UTC, temnik15 commented on app/src/main/res/layout/search_view_layout.xml
> +        android:layout_width="14dp"
размеры в ресурсы

2020-12-22 11:30 UTC, temnik15 commented on app/src/main/res/layout/search_view_layout.xml
> +        android:layout_width="14dp"
хотя, если используется только здесь

2020-12-23 05:20 UTC, Shiplayer approved these changes

2020-12-23 05:20 UTC, merged