Add fetching user and workspaces, also divide workspaces into cut ver…
codex-team/hawk.android pull request #49
Opened 2020-12-13 16:30 UTC by YorkIsMine

…sion and projects

2020-12-13 17:26 UTC, Shiplayer requested changes
Вообще, я предполагал, что интеракторы будут взаимодействовать с провайдерами (в плане получения данных), а вьюмодел с провайдером

2020-12-13 17:26 UTC, Shiplayer commented on app/src/main/graphql/so/codex/hawk/GetWorkspacesQuery.graphql
> +        }
Минор: вроде как, мы нам еще надо знать количество ошибок в проекте с описанием

2020-12-13 17:26 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/FetchWorkspacesInteractor.kt
> +            .map {
может стоит сделать mapNotNull?

2020-12-13 17:26 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/FetchWorkspacesInteractor.kt
> +            .observeOn(AndroidSchedulers.mainThread())
зачем сразу на главном потоке все делать?

2020-12-13 17:26 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/FetchWorkspacesInteractor.kt
> +                        w!!.projects?.map { q ->
а почему тут мы уже с уверенностью можем сказать, что тут не будет null?

2020-12-13 17:26 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/UserInfoInteractor.kt
> +                val user = it!!.data!!.me!!
может не стоит быть на столько уверенным, что мы не получим null?

2020-12-13 17:26 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/data_providers/WorkspaceProvider.kt
> +}
вообще, я предполагал, что сами провайдеры будут ходить в сеть и иметь подписки и сабджекты на ответы

2020-12-13 17:26 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/entity/Workspace.kt
> +    var projects: List<Project>? = null
почему null, а не listOf()?

2020-12-15 06:31 UTC, Shiplayer commented
`WorkspaceProvider` должен использовать апи для получения ответа и сохранения ответа в BehaviorSubject, также должен предоставлять observable с Workspace (без проектов) для интерактора

2020-12-16 06:46 UTC, Shiplayer requested changes

2020-12-16 06:46 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/UserInfoInteractor.kt
> +                it.data?.me?.let { u ->
тут map может вернуть null, зачем нам это?

2020-12-16 06:46 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/data_providers/WorkspaceProvider.kt
> +                        it.data?.workspaces?.mapNotNull { w ->
зачем делать у списка mapToNull, если он ни как не может вернуть null? а, вот map у Observable вполне может

2020-12-16 06:46 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/data_providers/WorkspaceProvider.kt
> +        return behaviorSubject.subscribeOn(Schedulers.io())
получается, что тут такой код, что никогда не будет вызван запрос, потому что в subject никогда не придет значение

2020-12-16 06:46 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/data_providers/WorkspaceProvider.kt
> +                NetworkProvider.getApolloClient().rxQuery(WorkspacesQuery())
и вообще, если у нас токен протухнет, то мы даже не сможем сделать повторно запрос

2020-12-16 06:47 UTC, YorkIsMine commented on app/src/main/java/so/codex/hawk/data_providers/WorkspaceProvider.kt
> +                        it.data?.workspaces?.mapNotNull { w ->
mapNotNull нет у обсервера

2020-12-16 06:48 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/data_providers/WorkspaceProvider.kt
> +                        it.data?.workspaces?.mapNotNull { w ->
так сделай тогда

2020-12-16 06:48 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/data_providers/WorkspaceProvider.kt
> +                        it.data?.workspaces?.mapNotNull { w ->
что тебе мешает заранее отфильтровать?

2020-12-16 12:43 UTC, temnik15 requested changes

2020-12-16 12:43 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/UserInfoInteractor.kt
> +     * @return [User] wrapped in [Observable]
Добавь пустую строку между описание метода и @return, дабы придерживаться единого стиля оформления.

2020-12-16 12:43 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/data_providers/WorkspaceProvider.kt
> +     * @return workspaces without projects inside
Тоже самое, отдели основное описание и описание возвращаемого значения

2020-12-16 12:43 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/data_providers/WorkspaceProvider.kt
> +                NetworkProvider.getApolloClient().rxQuery(WorkspacesQuery())
@YorkIsMine глянь как сделана работа с subject в Interactor что я писал (LoginInteractor например), мы там с Антоном обсуждали и пришли к решению которое при ошибке возвращает ту же цепочку.

2020-12-16 12:43 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/data_providers/WorkspaceProvider.kt
> +     * @return workspaces without projects inside
И просмотри весь код, еще ниже нашел такие же случаи.

2020-12-16 20:15 UTC, Shiplayer commented
Кстати, у каждого коммита должна быть номер задачи

2020-12-24 06:35 UTC, closed without merging