create recycler on main activity
codex-team/hawk.android pull request #52
Opened 2020-12-24 14:53 UTC by temnik15

2020-12-24 18:37 UTC, Shiplayer requested changes

2020-12-24 18:37 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/domain/providers/ProjectProvider.kt
> +                    }
почему бы не сделать так?
```suggestion
            .observeOn(Schedulers.io())
            .map { workspaces ->
                workspaces.fold(listOf<Project>()) { acc, value ->
                    acc + value.projects
                }
            }
            .subscribe { projectList ->
                subject.onNext(projectList)
            }
```

2020-12-24 18:37 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/extensions/convert/convertToUiModel.kt
> +}
зачем это выносить куда-то в отдельный файл, если это используется исключительно только в одном файле или планируется еще где-то использоваться?

2020-12-24 18:37 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/extensions/convert/convertToUiModel.kt
> +}
аналогично, что и выше

2020-12-24 18:37 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/extensions/domain/Utils.kt
> +}
почему все методы в данном файле должны быть без класса? может стоит их всех обернуть в object Utils?

2020-12-24 18:37 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/data/UiProject.kt
> +) {
почему бы его не сделать data class?

2020-12-24 18:37 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/main/MainActivity.kt
> +        item.context = applicationContext
как-то не очень(

2020-12-24 18:37 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/main/MainActivity.kt
> +        window.clearFlags(WindowManager.LayoutParams.FLAG_TRANSLUCENT_NAVIGATION)
для чего это?

2020-12-24 18:37 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/main/MainActivity.kt
> +        window.clearFlags(WindowManager.LayoutParams.FLAG_TRANSLUCENT_NAVIGATION)
разве мы не можем это сделать с помощью стилей для темы активити?

2020-12-24 18:37 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/main/ProjectAdapter.kt
> +class ProjectAdapter : RecyclerView.Adapter<ProjectAdapter.ViewHolder>() {
давай мы тут будем использовать DiffUtils?

2020-12-24 18:37 UTC, Shiplayer commented on app/src/main/res/layout/search_view_layout.xml
> +        android:background="@color/defaultBackgroundV1"
может как-то получше можно назвать?)

2020-12-24 18:42 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/ui/main/MainActivity.kt
> +        item.context = applicationContext
Ну так мы ж договорились что тащим applicationContext в ViewModel?

2020-12-24 18:43 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/main/MainActivity.kt
> +        item.context = applicationContext
да, но не хотелось бы таким способом

2020-12-24 18:44 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/ui/main/MainActivity.kt
> +        window.clearFlags(WindowManager.LayoutParams.FLAG_TRANSLUCENT_NAVIGATION)
Это  возвращает непрозрачность для navigation bar и status bar . Сделать с помощью стилей можем, но стоит ли делать абсолютно идентичный стиль только без одного флага? Проще ведь просто вот так убрать этот флаг

2020-12-24 18:45 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/ui/main/ProjectAdapter.kt
> +class ProjectAdapter : RecyclerView.Adapter<ProjectAdapter.ViewHolder>() {
Ок, но смысла в этом мало, активного изменения элементов recycler по логике здесь не планируется и выигрыша никакого нам не даст

2020-12-24 18:45 UTC, temnik15 commented on app/src/main/res/layout/search_view_layout.xml
> +        android:background="@color/defaultBackgroundV1"
Оу, забыл, поправлю

2020-12-24 18:46 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/main/MainActivity.kt
> +        window.clearFlags(WindowManager.LayoutParams.FLAG_TRANSLUCENT_NAVIGATION)
но у нас же может быть не один экран, проще уж тогда на LoginActivity это сделать, так как только там это используется

2020-12-24 18:47 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/ui/main/MainActivity.kt
> +        item.context = applicationContext
Хм, что то не так в способе передачи ? 
Мы конечно можем рассмотреть и вариант с AndroidViewModel

2020-12-24 18:47 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/main/ProjectAdapter.kt
> +class ProjectAdapter : RecyclerView.Adapter<ProjectAdapter.ViewHolder>() {
да, а если мы добавим выбор воркспейса? мы уже должны будем отобразить список с проектами по выбранному воркспейсу

2020-12-24 18:50 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/ui/main/ProjectAdapter.kt
> +class ProjectAdapter : RecyclerView.Adapter<ProjectAdapter.ViewHolder>() {
Забыл о таком функционале) Добавлю diff util

2020-12-25 10:14 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/ui/main/MainActivity.kt
> +        item.context = applicationContext
Немного костыльный, но тоже вариант, все что нам нужно от контекста это side view из dimens и dencity. Пожалуй я лучше буду их передавать во viewModel, а не context

2020-12-25 11:20 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/extensions/convert/convertToUiModel.kt
> +}
Согласен, удалил

2020-12-25 11:23 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/ui/main/MainActivity.kt
> +        item.context = applicationContext
а не, еще необходим цвет для текста из ресурсов...Вероятно можно создать некую модель CreateIconConfig и передавать её с view во ViewModel, но звучит также не очень, что думаешь?

2020-12-25 11:32 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/ui/main/MainActivity.kt
> +        window.clearFlags(WindowManager.LayoutParams.FLAG_TRANSLUCENT_NAVIGATION)
Подумал, экрана с прозрачными navigation и status bar два, решил чтобы не вносить путаницу сделать две темы, с прозрачностью и без прозрачности

2020-12-25 12:07 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/main/MainActivity.kt
> +        item.context = applicationContext
да легче написать класс, который будет создан в классе HawkApplication и при создании данного объекта, мы сразу получим необходимые значения, цвета и строки (только, возможно, стоит разделить их на 3 отдельных класса)

2020-12-25 21:20 UTC, YorkIsMine approved these changes

2020-12-25 21:40 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/login/LoginActivity.kt
> +        setTheme(R.style.AppThemeWithTranslucentNavigation)
можно же указать тему для активити прямо в AndroidManifest.xml

2020-12-25 21:40 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/main/projectlist/ProjectCallback.kt
> +    }
в котлине `==` равносильно `equals`, а проверять содержимое там и там, как-то не логично, предлагаю для метода `areItemsTheSame` вместо `==` сделать `===`, так как тут уже будет проверка по ссылке, а не по содержимому

2020-12-25 21:42 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/ui/main/projectlist/ProjectCallback.kt
> +    }
Так в первом случае equals только по id  а во втором по всему объекту

2020-12-25 21:43 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/main/projectlist/ProjectCallback.kt
> +    }
а, да, что-то не заметил, но это тоже не гарантирует нам, что содержимое объекта останется тоже самое

2020-12-25 21:43 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/main/projectlist/ProjectCallback.kt
> +    }
поменяешь название, айдишник то не поменяется

2020-12-25 21:45 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/ui/main/projectlist/ProjectCallback.kt
> +    }
Ну так и равенство ссылок ничего не даст если поменяю название) для проверки изменения содержимого как раз и предназначен второй метод, а первый только установить что это физически тот же самый объект, но в целом я не против и ссылки проверять, просто по id как то читабельнее

2020-12-25 21:46 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/main/projectlist/ProjectCallback.kt
> +    }
не, ладно, убедил, давай оставим id

2020-12-25 21:59 UTC, Shiplayer approved these changes

2020-12-25 22:09 UTC, merged