Add filtering projects
codex-team/hawk.android pull request #57
Opened 2020-12-27 04:48 UTC by YorkIsMine

2020-12-27 08:19 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/ui/main/projectlist/ProjectCallback.kt
> +        return oldItem.id === newItem.id
Не понял зачем оно все таки надо) === только вводит в заблуждение,   если все таки считаешь что надо проверять ссылки, то == с этим тоже прекрасно справится внутри equals)

2020-12-27 08:27 UTC, YorkIsMine commented on app/src/main/java/so/codex/hawk/ui/main/projectlist/ProjectCallback.kt
> +        return oldItem.id === newItem.id
Внутри equals? В котлине == это и есть equals. Но оно не сравнивает по ссылкам и для этого нужен ===

2020-12-27 08:48 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/ui/main/projectlist/ProjectCallback.kt
> +        return oldItem.id === newItem.id
equals внутри одним из первых шагов как раз и сравнивает по ссылкам)

2020-12-27 19:52 UTC, Shiplayer requested changes
Необходимо переделать

2021-02-03 19:04 UTC, Shiplayer requested changes

2021-02-03 19:04 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/main/projectlist/ProjectCallback.kt
> +        return oldItem.id === newItem.id
тут все таки лучше оставить `==` вместо `===`

2021-02-03 19:04 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/main/projectlist/FilterProjectUtils.kt
> +object FilterProjectUtils {
можно сделать обычным классом, создать инстанс во `MainViewModel` и предоставить этот класс в активити, чтобы установить фильтрацию

2021-02-03 19:04 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/main/MainActivity.kt
> +            FilterProjectUtils.filterableList = model.projects
как то странно получается, сабмитить список в адаптер, потом устанавливать его для фильтрации, где потом все равно будет перезаписан засабмиченный список, почему тогда данную фильтрацию не сделать в `MainViewModel`?

2021-02-15 05:31 UTC, closed without merging