Feature/hawk 39/add badge
codex-team/hawk.android pull request #59
Opened 2021-01-04 09:18 UTC by Shiplayer

#39
Добавил вьюшку для бейджа
Добавил вспомогательный класс для предоставления сокращенной записи числа
Добавил вьюшку на главных экран

2021-01-04 13:34 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/utils/ShortNumberUtils.kt
> +object ShortNumberUtils {
У меня два вопроса по данному классу:
1. А корректно ли он работает с количество отображаемых event, если становить 3456 отображено будет 3K,  хотя по предоставленному дизайну ожидается  3 456, а для 345776 будет отображено 345К,  хотя по дизайну ожидается 345.7K. Логику твоего отображения не понял)

2. Уже есть Utils сокращающий правильно

2021-01-04 15:03 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/utils/ShortNumberUtils.kt
> +object ShortNumberUtils {
Я взял реализацию с библиотеки, которая используется на сайте

2021-01-08 15:56 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/custom/views/badge/BadgeViewModel.kt
> +    val count: Long = BadgeView.UNDEFINED_COUNT,
Стоит наверное все таки уточнить у Петра, какое отображение он ожидает увидеть. Твой вариант тоже выглядит хорошо, но все же я бы уточнил).

А тут добавь в адаптер проверку видимости количества events, если count==0

2021-01-25 20:42 UTC, temnik15 approved these changes

2021-01-27 12:34 UTC, YorkIsMine requested changes

2021-01-27 12:34 UTC, YorkIsMine commented on app/src/main/java/so/codex/hawk/custom/views/badge/BadgeView.kt
> +    fun update(model: BadgeViewModel) {
давай лучше модельки для вьюшки называть <Имя>UiModel. А то немного сбивает

2021-01-28 12:13 UTC, YorkIsMine approved these changes

2021-01-28 13:54 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/utils/ShortNumberUtils.kt
> +object ShortNumberUtils {
Все таки оставляем ту реализацию которая есть? Петр подтвердил что должно быть соответствие реализации и дизайна.

2021-01-28 14:40 UTC, temnik15 commented on app/src/main/res/layout/badge_layout.xml
> +        android:id="@+id/tv_badge_counter"
Сейчас еще запустил посмотрел как выглядит badge. Как думаешь, может стоит добавить paddingStart/End? Посмотри на ширину badge при количестве events<10 здесь и в figma.

2021-01-30 22:04 UTC, Shiplayer commented on app/src/main/res/layout/badge_layout.xml
> +        android:id="@+id/tv_badge_counter"
посмотрел, подправил отступ сверху/снизу, все остальное, вроде как, ок

2021-01-30 22:09 UTC, merged