created squircleDrawable and changed the use of SquircleImageView
codex-team/hawk.android pull request #61
Opened 2021-01-27 18:55 UTC by temnik15

First new, second old
![device-2021-01-27-213208](https://user-images.githubusercontent.com/45372245/106039546-4c152500-60ea-11eb-8744-5d9b2807eda7.png)

2021-01-27 19:04 UTC, YorkIsMine approved these changes

2021-01-27 19:07 UTC, temnik15 commented
Добавлю сейчас еще оптимизацию в адаптер

2021-01-27 21:08 UTC, Shiplayer requested changes

2021-01-27 21:08 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/custom/views/SquircleDrawable.kt
> +        paintShader.isAntiAlias = true
Может это стоит определить один раз в init или там где объявили переменные с помощью apply?

2021-01-27 21:08 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/custom/views/SquircleDrawable.kt
> +        val yN = 1 - (abs(x / radius).pow(n))
тут может быть эксепшне, если кто-то решит поменять радиус на 0, но это такое себе, минорное замечание

2021-01-27 21:08 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/data/UiProject.kt
> +    var imageDrawable: SquircleDrawable? = null
почему это должно быть var? почему оно не может быть иммутабельным?

2021-01-27 21:08 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/data/UiProject.kt
> +    var imageDrawable: SquircleDrawable? = null
мы не можем заранее предоставить icon по умолчанию?

2021-01-27 21:08 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/main/projectlist/ProjectAdapter.kt
> +                    loadIcon(item)
почему бы ее не загрузить до того, как мы будет ее вставлять во вьюшку?

2021-01-28 11:34 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/custom/views/SquircleDrawable.kt
> +        paintShader.isAntiAlias = true
done

2021-01-28 11:37 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/custom/views/SquircleDrawable.kt
> +        val yN = 1 - (abs(x / radius).pow(n))
n или радиус? Хотя не важно. Добавлю условие что createPath не будет тратить время если n или radius ==0

2021-01-28 11:59 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/ui/data/UiProject.kt
> +    var imageDrawable: SquircleDrawable? = null
done

2021-01-28 14:02 UTC, temnik15 commented
![device-2021-01-28-165646](https://user-images.githubusercontent.com/45372245/106148241-df516780-6189-11eb-98b3-4032bf7d3f9c.png)

2021-01-30 22:14 UTC, Shiplayer commented on app/src/main/res/layout/project_list_item.xml
> +        android:scaleType="centerCrop" />
вроде мы решили программно кропать

2021-01-30 22:14 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/main/MainViewModel.kt
> +                                it.id, it.name, it.description, it.image, it.unreadCount,
выровняй параметры в один столбик

2021-01-30 22:14 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/main/MainViewModel.kt
> +                                )
аналогично, в один столбик

2021-02-02 10:13 UTC, Shiplayer approved these changes

2021-02-02 17:25 UTC, merged