#62: fix problem with splash screen, update refresh token interactor
codex-team/hawk.android pull request #63
Opened 2021-01-28 08:58 UTC by Shiplayer

#62 Подправил RefreshTokenInterator, чтобы больше не получалось такого, что мы просим его обновить токен, а он еще не успел подписаться на subject.

2021-01-28 14:10 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/ui/login/LoginActivity.kt
> +                        "Ошибка входа",
Давай сразу в ресурсы вынесем строки?

2021-01-28 14:10 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/ui/main/MainActivity.kt
>          item.context = applicationContext
вот тут убери установку контекста. Берем теперь же с HawkApp

2021-01-28 14:10 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/login/LoginActivity.kt
> +                        "Ошибка входа",
это твой код был в debug-app

2021-01-28 14:13 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/ui/login/LoginActivity.kt
> +                        "Ошибка входа",
:D ну ладно..надо только уточнить конкретный формат уведомления

2021-01-30 22:09 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/login/LoginActivity.kt
> +                        "Ошибка входа",
вынес в strings.xml

2021-01-30 22:09 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/main/MainActivity.kt
>          item.context = applicationContext
убрал

2021-02-02 09:15 UTC, temnik15 approved these changes

2021-02-03 10:30 UTC, YorkIsMine requested changes

2021-02-03 10:30 UTC, YorkIsMine commented on app/src/main/java/so/codex/hawk/domain/providers/AuthProvider.kt
> +class AuthProvider {
Нейминг. Вообще не очень очевидно, что этот класс дает именно инфу об авторизации. Как вариант можно бы было назвать AuthInfoUtils или AuthInfoProvider. Плюс сам класс напрашивается быть не классом, а object каким нибудь, ибо он просто предоставляет общую инфу об авторизации

2021-02-03 10:30 UTC, YorkIsMine commented on app/src/main/java/so/codex/hawk/domain/refresh/RefreshTokenInteractorImpl.kt
> +    private val refreshEventSubject = BehaviorSubject.create<RefreshEvent>()
а почему кстати Behaviour почти всегда берешь?

2021-02-03 10:36 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/domain/providers/AuthProvider.kt
> +class AuthProvider {
я его планировал синглтоном сделать, когда буду di завозить

2021-02-03 10:36 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/domain/refresh/RefreshTokenInteractorImpl.kt
> +    private val refreshEventSubject = BehaviorSubject.create<RefreshEvent>()
потому что нужно последнее событие, если мы подключились позднее, чем сперва подключились и засабмитили новый элемент

2021-02-03 10:38 UTC, YorkIsMine commented on app/src/main/java/so/codex/hawk/domain/refresh/RefreshTokenInteractorImpl.kt
> +    private val refreshEventSubject = BehaviorSubject.create<RefreshEvent>()
Behaviour отдает не последнее событие. Последнее отдает AsyncSubject http://reactivex.io/RxJava/javadoc/rx/subjects/AsyncSubject.html

2021-02-03 20:02 UTC, YorkIsMine approved these changes

2021-02-03 20:02 UTC, merged