#67:Created navigation layout
codex-team/hawk.android pull request #70
Opened 2021-02-05 19:10 UTC by temnik15

1. Created navigation layout.
2. Created workspace_list_item.
3. Added recycler for workspaces list.
4. Added visibility on click workspace.
5. Added debug value for user account.

2021-02-05 20:08 UTC, Shiplayer requested changes

2021-02-05 20:08 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/main/workspacelist/WorkspaceAdapter.kt
> +class WorkspaceAdapter(val listener: OnWorkspaceClickListener) :
на самом деле, мне бы не хотелось так делать, так как надо будет делать какое то событие еще во вьюмоделе, почему бы нам сразу в UiWorkspace не сделать callback, если будет совершен клик? не надо будет пробрасывать и мы сразу можем его обработать, вроде как, даже неплохо

2021-02-05 20:08 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/main/workspacelist/WorkspaceAdapter.kt
> +            view.setOnClickListener(this)
ой не хочется мне так делать, что-то
можешь посмотреть методы, которые есть у ресайклера, у него есть методы onBindViewHolder, в котором должны быть установлены данные и метод onViewRecycled, когда вьюшка кладется обратно в пулл и необходимо ее почистить (хотя бы убрать callback)

2021-02-05 20:08 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/main/workspacelist/WorkspaceCallback.kt
> +        return oldItem.workspaceName == newItem.workspaceName
может workspaceId?

2021-02-05 20:08 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/main/workspacelist/WorkspaceAdapter.kt
> +    private var selectedView: View? = null
не хорошо так делать, потому что если будет большой список, то у тебя будет выбираться каждый n воркспейсов, где n количество вьюшек, которые влезли в твой экран

2021-02-05 20:08 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/main/workspacelist/WorkspaceAdapter.kt
> +    private var selectedView: View? = null
лучше запомни его id

2021-02-05 20:08 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/main/workspacelist/WorkspaceAdapter.kt
> +        private var workspaceId: String = ""
зачем тогда тут это поля?

2021-02-05 20:08 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/main/workspacelist/WorkspaceAdapter.kt
> +        private var workspaceId: String = ""
для чего нам хранить id?

2021-02-05 20:08 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/main/workspacelist/WorkspaceAdapter.kt
> +        private var workspaceId: String = ""
пусть уж лучше установка клика будет внутри bind

2021-02-05 20:11 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/ui/main/workspacelist/WorkspaceAdapter.kt
> +class WorkspaceAdapter(val listener: OnWorkspaceClickListener) :
Надо обсудить дополнительно. Пока не понимаю как можно обработать выбор workspace внутри UiWorkspace. Нам ведь необходимо каким-то образом отфильтровать отображаемые проекты

2021-02-05 20:12 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/ui/main/workspacelist/WorkspaceCallback.kt
> +        return oldItem.workspaceName == newItem.workspaceName
да, забыл, писал когда еще не добавил поля в модель

2021-02-05 20:13 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/ui/main/workspacelist/WorkspaceAdapter.kt
> +    private var selectedView: View? = null
Не понял..почему n? запоминается только конкретная view которая была выбрана при клике

2021-02-05 20:14 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/ui/main/workspacelist/WorkspaceAdapter.kt
> +        private var workspaceId: String = ""
Понял. установку обработчика поправлю. Id думал хранить для того чтобы передать коллбэком при клике в обработчик

2021-02-05 20:16 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/main/workspacelist/WorkspaceAdapter.kt
> +    private var selectedView: View? = null
да, но это ресайклер вью, он не создает на каждый элемент в списке вьюшку, он создает фиксированное количество, которое может влезть на экран +2 вьюшки на запас.
Можешь сам проверить при воркспейсах больше 20

2021-02-05 20:19 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/ui/main/workspacelist/WorkspaceAdapter.kt
> +    private var selectedView: View? = null
Так на это фиксированное количество здесь я  как раз и рассчитываю) с вопросом выше думаю потом голосом сможем обсудить ?

2021-02-08 20:35 UTC, YorkIsMine requested changes

2021-02-08 20:35 UTC, YorkIsMine commented on app/src/main/res/layout/main_header.xml
> +    android:background="@color/colorMainHeader"
а есть ли единый стайл, по которому мы называем ресурсы, айдишники и тд? А то в camel case, то через _

2021-02-08 20:35 UTC, YorkIsMine commented on app/src/main/res/layout/workspace_list_item.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
А что мешает нам это во FrameLayout обернуть?

2021-02-08 20:35 UTC, YorkIsMine commented on app/src/main/res/values/colors.xml
> +    <color name="colorStandardLight">#DBE6FF</color>
Ну также, как и выше. Стиль именования

2021-02-08 20:37 UTC, Shiplayer commented on app/src/main/res/layout/workspace_list_item.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
Наверное то, что нам не надо, чтобы текст накладывался на картинку?

2021-02-08 20:38 UTC, YorkIsMine commented on app/src/main/res/layout/workspace_list_item.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
там гравити есть в центре, картинку не заденет, если текст будет расти вправо. А он будет так расти

2021-02-13 20:16 UTC, YorkIsMine approved these changes

2021-02-16 14:51 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/domain/providers/ExternalSourceWorkspaceImpl.kt
> +    private val NO_SELECTED_WORKSPACE = ""
не думаю, что лучше ее делать приватной, сделай публичной

2021-02-16 14:51 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/main/MainViewModel.kt
> +                }.map { it.toUiProject() }
почему сюда вынес? мы так на каждый чих будем мапить в ui модельку, почему мы не можем это сделать после `distinctUntilChanged`?

2021-02-16 14:51 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/main/MainViewModel.kt
> +            searchSubject.observeOn(Schedulers.io()),
мы уже используем trailing comma?)

2021-02-16 14:51 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/domain/providers/ProjectProvider.kt
> +                if (selectedWorkspaceId.isBlank()) {
может тут просто сравнить с `NO_SELECTED_WORKSPACE`?

2021-02-16 14:51 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/domain/providers/ProjectProvider.kt
> +                    workspaceList.find { it.id == selectedWorkspaceId }?.projects
сделай с новой строчки, а то можно не заметить `?.projects`

2021-02-16 14:51 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/main/DrawerViewModel.kt
> +                    )
давай сделаем расширение для Workspaces, чтобы разгрузить эту цепочку от формирования UI модели

2021-02-16 15:20 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/domain/providers/ExternalSourceWorkspaceImpl.kt
> +    private val NO_SELECTED_WORKSPACE = ""
done

2021-02-16 15:21 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/ui/main/MainViewModel.kt
> +                }.map { it.toUiProject() }
done

2021-02-16 19:42 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/domain/providers/WorkspaceProvider.kt
> +        val NO_SELECTED_WORKSPACE:String
Сделай его константой и определи его тут

2021-02-16 19:42 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/domain/providers/WorkspaceProvider.kt
> +        val NO_SELECTED_WORKSPACE:String
Может давай вынесем этот интерфейс в отдельный файл?

2021-02-16 19:42 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/domain/providers/WorkspaceProvider.kt
> +            .subscribeOn(Schedulers.io())
может тут лучше observeOn сделать

2021-02-16 19:42 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/main/MainViewModel.kt
> +                )
Может лучше это вынести в отдельную функцию и сделать map перед subscribe?

2021-02-16 19:42 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/main/workspacelist/WorkspaceAdapter.kt
> +            }
можно попробовать
```suggestion
            itemView.setOnClickListener(item::onClick)
```

2021-02-16 19:42 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/main/workspacelist/WorkspaceCallback.kt
> +}
у нас же получается, что это точно такой же DiffUtil, как и для проектов, может можно как-то обобщить?)

2021-02-17 16:42 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/domain/providers/WorkspaceProvider.kt
> +            .subscribeOn(Schedulers.io())
done

2021-02-17 16:43 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/ui/main/MainViewModel.kt
> +                )
Переделал модель. Неактуально. Новая модель будет чуть попозже

2021-02-17 16:59 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/ui/main/workspacelist/WorkspaceAdapter.kt
> +            }
забыл добавить последним коммитом... Добавлю)

2021-02-17 18:31 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/di/modules/ProjectModule.kt
> +        return ProjectProvider(workspaceProvider,source)
пробел бы после запятой

2021-02-17 18:31 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/domain/providers/ExternalSourceWorkspace.kt
> +    fun setSelectedWorkspace(workspaceId: String,workspaceName:String)
тоже пробел после запятой

2021-02-17 18:31 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/domain/providers/ExternalSourceWorkspace.kt
> +        const val NO_SELECTED_WORKSPACE:String = ""
пробел после двоеточия

2021-02-17 18:31 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/domain/providers/ExternalSourceWorkspace.kt
> +    fun setSelectedWorkspace(workspaceId: String,workspaceName:String)
пробел после двоеточия

2021-02-17 18:31 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/domain/providers/ExternalSourceWorkspaceImpl.kt
> +    private val currentWorkspaceNameSubject = BehaviorSubject.create<String>()
а нам действительно не достаточно Id?
Если нет, то может мы можем их как-то объединить, если планируется использовать их совместно?

2021-02-17 18:31 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/data/UiWorkspace.kt
> +    }
Почему нам нужен только хеш-код от workspaceId?

2021-02-17 18:31 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/main/DrawerViewModel.kt
> +    private val workspaceOnClick = { workspaceId: String,workspaceName:String ->
пробел после запятой и двоеточия

2021-02-17 18:31 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/main/DrawerViewModel.kt
> +                })
скобку с новой строки

2021-02-17 18:31 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/main/MainActivity.kt
> +        }
почему отделил? можно же оставить частью UiMainViewModel, так как она не меняется на каждый чих

2021-02-17 18:31 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/main/MainActivity.kt
> +        }
как то не хочется для каждого отдельного элемента делать модельку

2021-02-17 18:31 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/main/MainViewModel.kt
> +                    }
ну вот поэтому, мне больше нравился сабжект, который уже имеет простой Workspace

2021-02-17 18:31 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/main/lists/DiffItemCallback.kt
> +       return oldItem==newItem
пробелы

2021-02-17 18:31 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/main/lists/DiffItemCallback.kt
> +abstract class DiffItemCallback<T>: DiffUtil.ItemCallback<T>()  {
ну и такое себе обобщение)
Почему бы не ввести интерфейс `HasId`, принимать его тут как `T: HasId` и сразу определить тут необходимые методы?

2021-02-17 18:53 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/domain/providers/ExternalSourceWorkspaceImpl.kt
> +    private val currentWorkspaceNameSubject = BehaviorSubject.create<String>()
Да, нам действительно необходимо как то передать workspace name, так как в MainViewModel у нас уже нет информации о каком то конкретном   workspace. Я думал модифицировать workspace provider, чтобы он умел отдавать название workspace по переданному id. Думаю переделаю на данный вариант .

2021-02-17 18:53 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/ui/data/UiWorkspace.kt
> +    }
Взял как наиболее уникальное поле

2021-02-17 18:55 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/ui/main/MainActivity.kt
> +        }
Вот как раз  теперь UiMainViewModel меняется на каждый чих) При выборе workspace в drawer модель UiMainViewModel обновляется, можно управлять отображением и загрузки, а также приходит новый заголовок в виде названия выбранного workspace

2021-02-17 18:56 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/ui/main/MainViewModel.kt
> +                    }
Пока не понял, уточню в телеграмме

2021-02-19 22:29 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/ui/main/workspacelist/WorkspaceAdapter.kt
> +            }
Это не работает как ожидается, так как onClick не метод, а свойство

2021-02-19 22:30 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/domain/providers/ExternalSourceWorkspaceImpl.kt
> +    private val currentWorkspaceNameSubject = BehaviorSubject.create<String>()
done

2021-02-20 13:01 UTC, Shiplayer approved these changes

2021-02-20 20:25 UTC, merged