#56: add filter for projects
codex-team/hawk.android pull request #72
Opened 2021-02-12 22:38 UTC by Shiplayer

Добавил фильтрацию проектов

2021-02-13 20:12 UTC, YorkIsMine requested changes

2021-02-13 20:12 UTC, YorkIsMine commented on app/src/main/java/so/codex/hawk/ui/main/MainActivity.kt
> +        viewModel.observeUiProjects().observe(this, ::handleUiProjects)
А почему возвращаете лайв и его потом сразу же обсервите? Почему бы не сделать так, чтобы вьюмодель возвращала некий обьект типа State с нужными значением и в зависимости от ивента мы делали бы какие-нибудь операции?

2021-02-13 20:12 UTC, YorkIsMine commented on app/src/main/java/so/codex/hawk/ui/main/MainViewModel.kt
> +                projectList.map {
Может сразу маппер написать по типу toSomeEntity, а то код распухает сильно

2021-02-14 18:54 UTC, temnik15 approved these changes

2021-02-14 18:54 UTC, temnik15 commented on app/src/main/java/so/codex/hawk/ui/data/UiMainViewModel.kt
> +import so.codex.hawk.custom.views.search.HawkSearchViewModel
Давай переименуем. ViewModel сбивает

2021-02-14 19:18 UTC, YorkIsMine approved these changes

2021-02-15 05:14 UTC, Shiplayer commented on app/src/main/java/so/codex/hawk/ui/data/UiMainViewModel.kt
> +import so.codex.hawk.custom.views.search.HawkSearchViewModel
сделал

2021-02-15 05:31 UTC, merged